#!/usr/bin/env python3
"""
Validation Script
=================
Reads Verilog simulation output and compares against Python reference model.
Reports pass/fail for each convolution window.

Usage:
    1. Run the Verilog simulation first (bash sim/run_simulation.sh)
    2. Run this script: python3 python/validation_script.py

The script validates:
    - Single-window convolution (matching accelerator's fixed test data)
    - Full convolution output (if test vectors were generated)
"""

import numpy as np
import os
import sys


def validate_single_window():
    """
    Validate the single-window convolution result that the accelerator computes.
    Uses the same fixed values as the Verilog accelerator module.
    """
    print("=" * 50)
    print(" Validation: Single-Window Convolution")
    print("=" * 50)
    print()

    # Same values as convolution_accelerator.v
    input_window = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], dtype=np.int64)

    kernel = np.array([
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]
    ], dtype=np.int64)

    expected = np.sum(input_window * kernel)
    print(f"Input window:\n{input_window}")
    print(f"Kernel:\n{kernel}")
    print(f"Expected result: {expected}")
    print()

    # The accelerator should produce: 1+3+5+7+9 = 25
    if expected == 25:
        print("[PASS] Reference model computes 25 (matches accelerator design)")
    else:
        print(f"[FAIL] Expected 25 but got {expected}")

    print()
    return expected


def validate_test_vectors():
    """
    Validate test vectors generated by test_vector_generator.py.
    """
    print("=" * 50)
    print(" Validation: Generated Test Vectors")
    print("=" * 50)
    print()

    sim_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "sim")

    input_path = os.path.join(sim_dir, "test_input.mem")
    kernel_path = os.path.join(sim_dir, "test_kernel.mem")
    expected_path = os.path.join(sim_dir, "test_expected.mem")

    # Check if test vector files exist
    if not all(os.path.exists(p) for p in [input_path, kernel_path, expected_path]):
        print("[SKIP] Test vector files not found.")
        print("       Run: python3 python/test_vector_generator.py first")
        return

    # Read input matrix
    input_vals = []
    with open(input_path, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("//"):
                input_vals.append(int(line, 16))

    # Read kernel
    kernel_vals = []
    with open(kernel_path, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("//"):
                kernel_vals.append(int(line, 16))

    # Read expected output
    expected_vals = []
    with open(expected_path, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("//"):
                expected_vals.append(int(line, 16))

    # Reshape
    input_size = int(np.sqrt(len(input_vals)))
    kernel_size = int(np.sqrt(len(kernel_vals)))

    input_matrix = np.array(input_vals).reshape(input_size, input_size)
    kernel = np.array(kernel_vals).reshape(kernel_size, kernel_size)

    # Recompute convolution
    out_h = input_size - kernel_size + 1
    out_w = out_h
    computed = np.zeros((out_h, out_w), dtype=np.int64)
    for i in range(out_h):
        for j in range(out_w):
            computed[i, j] = np.sum(input_matrix[i:i+kernel_size, j:j+kernel_size] * kernel)

    computed_flat = computed.flatten()
    expected_arr = np.array(expected_vals)

    print(f"Input ({input_size}x{input_size}):\n{input_matrix}")
    print(f"Kernel ({kernel_size}x{kernel_size}):\n{kernel}")
    print(f"Computed:\n{computed}")
    print(f"Expected:\n{expected_arr.reshape(out_h, out_w)}")
    print()

    # Compare
    all_pass = True
    for idx in range(len(expected_vals)):
        if computed_flat[idx] == expected_arr[idx]:
            print(f"  [PASS] Output[{idx}] = {computed_flat[idx]}")
        else:
            print(f"  [FAIL] Output[{idx}] computed={computed_flat[idx]}, expected={expected_arr[idx]}")
            all_pass = False

    print()
    if all_pass:
        print("[PASS] All test vectors validated successfully!")
    else:
        print("[FAIL] Some test vectors did not match.")

    return all_pass


def main():
    print()
    print("###################################################")
    print("#  RISC-V Convolution Accelerator Validation Suite #")
    print("###################################################")
    print()

    validate_single_window()
    validate_test_vectors()

    print()
    print("Validation complete.")


if __name__ == "__main__":
    main()
